=== MrFilip26/bakalarka/Jim/moves/moves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/moves"
        xmlns:tns="http://www.example.org/moves" elementFormDefault="qualified">

  <element name="robot">
    <complexType>
      <sequence>
        <element name="constants" type="tns:constants" minOccurs="0" maxOccurs="1"/>
        <element name="low_skills" type="tns:low_skills" minOccurs="1" maxOccurs="1"/>
        <element name="phases" type="tns:phases" minOccurs="1" maxOccurs="1"/>
      </sequence>
    </complexType>

    <key name="phaseNames">
      <selector xpath="./phases/phase"></selector>
      <field xpath="@name"></field>
    </key>
    <keyref name="lowSkillAutocomplete" refer="tns:phaseNames">
      <selector xpath="./low_skills/low_skill"></selector>
      <field xpath="@firstPhase"></field>
    </keyref>
  </element>

  <xs:simpleType name="typeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="kick"/>
      <xs:enumeration value="walk"/>
      <xs:enumeration value="fall"/>
      <xs:enumeration value="look"/>
      <xs:enumeration value="stand_up"/>
      <xs:enumeration value="rotation"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <complexType name="constants">
    <sequence>
      <element name="constant" type="tns:constant" minOccurs="1" maxOccurs="unbounded"></element>
    </sequence>
  </complexType>

  <complexType name="constant">
    <attribute name="name" use="required" type="string"/>
    <attribute name="value" use="required" type="double"/>
  </complexType>

  <complexType name="low_skills">
    <sequence>
      <element name="low_skill" type="tns:low_skill" minOccurs="1" maxOccurs="unbounded"></element>
    </sequence>
  </complexType>

  <complexType name="low_skill">
    <attribute name="name" type="string" use="required"></attribute>
    <attribute name="firstPhase" type="string" use="required"></attribute>
    <sequence>
      <element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"></element>
      <element name="author" type="xs:string" minOccurs="0" maxOccurs="1"></element>
      <element name="extendedFromMove" type="xs:string" minOccurs="0" maxOccurs="1"></element>
      <element name="description" type="xs:string" minOccurs="0" maxOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="phases">
    <sequence>
      <element name="phase" type="tns:phase" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="phase">
    <sequence>
      <element name="effectors" type="tns:effectors" maxOccurs="1"/>
      <element name="duration" type="int" maxOccurs="1"/>
      <sequence>
        <element name="finalize" type="string" minOccurs="0" maxOccurs="1"/>
      </sequence>
    </sequence>
    <attribute name="name" use="required"></attribute>
    <attribute name="next" use="required"></attribute>
    <attribute name="isFinal" type="boolean"></attribute>
    <attribute name="skipIfFlag" type="string"></attribute>
    <attribute name="setFlagTrue" type="string"></attribute>
    <attribute name="setFlagFalse" type="string"></attribute>
  </complexType>

  <attributeGroup name="end">
    <attribute name="end" type="int" use="required"></attribute>
  </attributeGroup>

  <element name="joint" abstract="true">
    <complexType>
      <attribute name="end" use="required" type="int"></attribute>
    </complexType>
  </element>

  <complexType name="effectors">
    <sequence minOccurs="0" maxOccurs="22">
      <element name="he1" type="tns:he1" minOccurs="0" maxOccurs="1"></element>
      <element name="he2" type="tns:he2" minOccurs="0" maxOccurs="1"></element>
      <element name="rle1" type="tns:rle1" minOccurs="0" maxOccurs="1"></element>
      <element name="rle2" type="tns:rle2" minOccurs="0" maxOccurs="1"></element>
      <element name="rle3" type="tns:rle3" minOccurs="0" maxOccurs="1"></element>
      <element name="rle4" type="tns:rle4" minOccurs="0" maxOccurs="1"></element>
      <element name="rle5" type="tns:rle5" minOccurs="0" maxOccurs="1"></element>
      <element name="rle6" type="tns:rle6" minOccurs="0" maxOccurs="1"></element>
      <element name="rae1" type="tns:rae1" minOccurs="0" maxOccurs="1"></element>
      <element name="rae2" type="tns:rae2" minOccurs="0" maxOccurs="1"></element>
      <element name="rae3" type="tns:rae3" minOccurs="0" maxOccurs="1"></element>
      <element name="rae4" type="tns:rae4" minOccurs="0" maxOccurs="1"></element>
      <element name="lle1" type="tns:lle1" minOccurs="0" maxOccurs="1"></element>
      <element name="lle2" type="tns:lle2" minOccurs="0" maxOccurs="1"></element>
      <element name="lle3" type="tns:lle3" minOccurs="0" maxOccurs="1"></element>
      <element name="lle4" type="tns:lle4" minOccurs="0" maxOccurs="1"></element>
      <element name="lle5" type="tns:lle5" minOccurs="0" maxOccurs="1"></element>
      <element name="lle6" type="tns:lle6" minOccurs="0" maxOccurs="1"></element>
      <element name="lae1" type="tns:lae1" minOccurs="0" maxOccurs="1"></element>
      <element name="lae2" type="tns:lae2" minOccurs="0" maxOccurs="1"></element>
      <element name="lae3" type="tns:lae3" minOccurs="0" maxOccurs="1"></element>
      <element name="lae4" type="tns:lae4" minOccurs="0" maxOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="joint" abstract="true">
    <attributeGroup ref="tns:end"></attributeGroup>
  </complexType>

  <complexType name="he1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="he2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle5">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle6">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle5">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle6">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>
</schema>

=== MrFilip26/bakalarka/Jim/moves/turn_left_60.xml
<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <constants>
    <!--konstanty sem-->
  </constants>
  <low_skills>
    <low_skill name="turn_left_60" firstPhase="turn_left_60_Phase0">
      <type>rotation</type>
      <author>Gabor Nagy (A55 kickers)</author>
      <extendedFromMove>turnleft90_faster_4</extendedFromMove>
      <description>Player turns 60 degrees to the left. Move is stable and fast.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="turn_left_60_Phase0" next="turn_left_60_Phase1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <lle6 end="0"/>
        <lle4 end="-20"/>
        <rle4 end="-40"/>
        <lle3 end="20"/>
        <rle6 end="-10"/>
        <lle5 end="20"/>
        <rle5 end="20"/>
        <rle3 end="40"/>
        <rae3 end="90"/>
        <lae1 end="-120"/>
        <rae1 end="-120"/>
        <lae4 end="-90"/>
        <rae4 end="90"/>
        <lae3 end="-90"/>
      </effectors>
      <duration>350</duration>
    </phase>
    <phase name="turn_left_60_Phase1" next="turn_left_60_Phase2">
      <effectors>
        <rle1 end="-40"/>
        <rle2 end="5"/>
        <rle3 end="20"/>
        <rle6 end="-15"/>
        <rle5 end="22"/>
        <lle1 end="-25"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="turn_left_60_Phase2" next="turn_left_60_Phase3">
      <effectors>
        <lle3 end="-10"/>
        <lle2 end="15"/>
        <lle4 end="-50"/>


        <rle1 end="-47"/>

        <lle1 end="-60"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_left_60_Phase3" next="turn_left_60_Phase4">
      <effectors>
        <lle3 end="-25"/>
        <lle2 end="5"/>
        <rle2 end="15"/>
        <lle4 end="-40"/>
        <rle5 end="20"/>
        <rle1 end="-55"/>
      </effectors>
      <duration>210</duration>
    </phase>
    <phase name="turn_left_60_Phase4" next="turn_left_60_Phase5">
      <effectors>
        <rle5 end="13"/>
        <lle5 end="25"/>
        <rle3 end="10"/>
        <rle4 end="-30"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_left_60_Phase5" next="turn_left_60_Phase6">
      <effectors>
        <lle6 end="6"/>
        <rle6 end="-5"/>
        <rle1 end="-50"/>
        <rle5 end="-5"/>
        <lle5 end="38"/>
        <lle4 end="-45"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_left_60_Phase6" next="turn_left_60_Phase7">
      <effectors>
        <lle3 end="-5"/>
        <lle1 end="0"/>
        <rle5 end="16"/>
        <lle5 end="30"/>
        <rle1 end="0"/>
        <lle3 end="20"/>
        <rle3 end="40"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="turn_left_60_Phase7" isFinal="true">
      <effectors>
        <lle2 end="0"/>
        <rle5 end="10"/>
        <lle5 end="10"/>
        <rle4 end="-20"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle4 end="-20"/>
        <rle3 end="20"/>
      </effectors>
      <duration>400</duration>
      <finalize>turn_left_60_Phase8</finalize>
    </phase>
    <phase name="turn_left_60_Phase8" isFinal="true">
      <effectors>

      </effectors>
      <duration>600</duration>
      <finalize>turn_left_60_Phase0</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/walk_slow.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <low_skills>
    <low_skill name="walk_slow" firstPhase="walk_slow_1">
      <type>walk</type>
      <author>Androids</author>
      <extendedFromMove>walk_fine</extendedFromMove>
      <description>Player performs straight walk. Move is stable but very slow.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="walk_slow_1" next="walk_slow_2">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="7"/>
        <lle2 end="-7"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-55"/>
        <lle4 end="-55"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="-7"/>
        <lle6 end="7"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="90"/>
        <lae3 end="-90"/>
        <rae4 end="45"/>
        <lae4 end="-45"/>
      </effectors>
      <duration>700</duration>
    </phase>
    <phase name="walk_slow_2" next="walk_slow_3">
      <effectors>
        <rle3 end="60"/>
        <rle4 end="-80"/>
        <rle5 end="40"/>
        <lle3 end="40"/>
        <lle4 end="-55"/>
        <lle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_slow_3" next="walk_slow_4">
      <effectors>
        <rle3 end="40"/>
        <rle4 end="-55"/>
        <rle5 end="30"/>
        <lle3 end="45"/>
        <lle4 end="-70"/>
        <lle5 end="40"/>
        <rae1 end="-110"/>
        <lae1 end="-70"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_slow_4" next="walk_slow_5">
      <effectors>
        <lle3 end="60"/>
        <lle4 end="-80"/>
        <lle5 end="40"/>
        <rle3 end="40"/>
        <rle4 end="-55"/>
        <rle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_slow_5" next="walk_slow_2" isFinal="true">
      <effectors>
        <lle3 end="40"/>
        <lle4 end="-55"/>
        <lle5 end="30"/>
        <rle3 end="45"/>
        <rle4 end="-70"/>
        <rle5 end="40"/>
        <rae1 end="-70"/>
        <lae1 end="-110"/>
      </effectors>
      <duration>150</duration>
      <finalize>walk_slow_6</finalize>
    </phase>
    <phase name="walk_slow_6" isFinal="true">
      <effectors>

        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>400</duration>
      <finalize>walk_slow_1</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/turn_right_90.xml
<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <constants>
    <!--konstanty sem-->
  </constants>
  <low_skills>
    <low_skill name="turn_right_90" firstPhase="turn_right_90_Phase0">
      <type>rotation</type>
      <author>Gabor Nagy (A55 kickers)</author>
      <extendedFromMove></extendedFromMove>
      <description>Player turns 90 degrees to the right. Move is stable and fast.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="turn_right_90_Phase0" next="turn_right_90_Phase1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <lle6 end="10"/>
        <rle6 end="0"/>
        <rle4 end="-20"/>
        <lle4 end="-50"/>
        <lle3 end="40"/>
        <rle3 end="20"/>
        <rle5 end="20"/>
        <lle5 end="20"/>
        <lae3 end="-90"/>
        <rae3 end="90"/>
        <rae1 end="-120"/>
        <lae1 end="-120"/>
        <lae4 end="-90"/>
        <rae4 end="90"/>
      </effectors>
      <duration>350</duration>
    </phase>
    <phase name="turn_right_90_Phase1" next="turn_right_90_Phase2">
      <effectors>
        <lle1 end="-45"/>
        <lle2 end="-5"/>
        <lle3 end="20"/>
        <lle6 end="15"/>
        <lle5 end="22"/>
        <rle1 end="-30"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="turn_right_90_Phase2" next="turn_right_90_Phase3">
      <effectors>
        <rle3 end="-10"/>
        <rle2 end="-15"/>
        <rle4 end="-50"/>


        <lle1 end="-64"/>

        <rle1 end="-90"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_right_90_Phase3" next="turn_right_90_Phase4">
      <effectors>
        <rle3 end="-25"/>
        <rle2 end="-5"/>
        <lle2 end="-15"/>
        <rle4 end="-40"/>
        <lle5 end="20"/>
        <lle1 end="-55"/>
      </effectors>
      <duration>210</duration>
    </phase>
    <phase name="turn_right_90_Phase4" next="turn_right_90_Phase5">
      <effectors>
        <lle5 end="10"/>
        <rle5 end="25"/>
        <lle3 end="10"/>
        <lle4 end="-30"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_right_90_Phase5" next="turn_right_90_Phase6">
      <effectors>
        <rle6 end="-11"/>
        <lle6 end="5"/>
        <lle1 end="-50"/>
        <lle5 end="-5"/>
        <rle5 end="35"/>
        <rle4 end="-45"/>
      </effectors>
      <duration>170</duration>
    </phase>
    <phase name="turn_right_90_Phase6" next="turn_right_90_Phase7">
      <effectors>
        <rle3 end="-5"/>
        <rle1 end="0"/>
        <lle5 end="16"/>
        <rle5 end="30"/>
        <lle1 end="0"/>
        <rle3 end="20"/>
        <lle3 end="40"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="turn_right_90_Phase7" next="turn_right_90_Phase8">
      <effectors>
        <rle2 end="0"/>
        <lle5 end="10"/>
        <rle5 end="10"/>
        <lle4 end="-20"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
        <rle1 end="0"/>
        <lle2 end="0"/>
        <rle4 end="-20"/>
        <lle3 end="20"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="turn_right_90_Phase8" next="turn_right_90_Phase_Pause" isFinal="true">
      <effectors>

      </effectors>
      <duration>0</duration>
      <finalize>turn_right_90_Phase9</finalize>
    </phase>
    <phase name="turn_right_90_Phase9" isFinal="true">
      <effectors>
        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>500</duration>
      <finalize>turn_right_90_Phase0</finalize>
    </phase>
    <phase name="turn_right_90_Phase_Pause" next="turn_right_90_Phase0">
      <effectors>

      </effectors>
      <duration>600</duration>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/kick_right_faster.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">

  <low_skills>
    <low_skill name="kick_right_faster" firstPhase="kick_right_faster_default">
      <type>kick</type>
      <author>Gabor Nagy (A55 kickers)</author>
      <extendedFromMove>kick_right_faster</extendedFromMove>
      <description>Player performs straight kick with left foot. Move is faster than kick_left_normal and stable. Player
        rotates 5Â° after kick
      </description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="kick_right_faster_default" next="kick_right_faster_Phase0">
      <effectors>
        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>500</duration>
    </phase>
    <phase name="kick_right_faster_Phase0" next="kick_right_faster_Phase1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rae3 end="0"/>
        <lae3 end="0"/>
        <rae4 end="0"/>
        <lae4 end="0"/>

        <!-- zakladna poloha noh -->
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle6 end="0"/>
        <lle6 end="0"/>

        <!-- ruky dolu -->
        <rae1 end="-70"/>
        <lae1 end="-70"/>

        <!-- pokrcenie kolien -->
        <rle4 end="-60"/>
        <lle4 end="-60"/>

        <rle5 end="38"/>
        <lle5 end="38"/>

        <!-- torzo -->
        <rle3 end="30"/>
        <lle3 end="30"/>
      </effectors>
      <duration>220</duration>
    </phase>
    <phase name="kick_right_faster_Phase1" next="kick_right_faster_Phase2">
      <effectors>
        <!-- ruka -->
        <lae1 end="-90"/>
        <lae2 end="-40"/>

        <!-- clenky -->
        <rle6 end="14"/>
        <lle6 end="16"/>

        <!-- bedra -->
        <rle2 end="-12"/>
        <lle2 end="-13"/>

        <!-- torzo -->
        <rle3 end="45"/>
        <lle3 end="45"/>

        <rle4 end="-65"/>

      </effectors>
      <duration>250</duration>

    </phase>
    <phase name="kick_right_faster_Phase2" next="kick_right_faster_Phase3">
      <effectors>
        <!-- koleno+clenok -->
        <lle2 end="-10"/>
        <lle4 end="-30"/>
        <rle4 end="-80"/>
        <lle5 end="18"/>
        <rle5 end="40"/>
        <rle6 end="10"/>


        <!-- bedro -->
        <lle3 end="50"/>
        <rle3 end="-20"/>

      </effectors>
      <duration>300</duration>
    </phase>
    <phase name="kick_right_faster_Phase3" next="kick_right_faster_Phase4">
      <effectors>
        <!-- bedro -->
        <lle3 end="-60"/>
        <rle3 end="60"/>

        <!-- koleno -->
        <lle4 end="0"/>
        <rle4 end="-78"/>

        <!-- spicka -->
        <lle5 end="16"/>
        <rle5 end="25"/>
      </effectors>
      <duration>290</duration>
    </phase>
    <phase name="kick_right_faster_Phase4" next="kick_right_faster_Phase5">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rae3 end="0"/>
        <lae3 end="0"/>
        <rae4 end="0"/>
        <lae4 end="0"/>

        <!-- zakladna poloha noh -->
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle6 end="0"/>
        <lle6 end="0"/>

        <!-- ruky dolu -->
        <rae1 end="-70"/>
        <lae1 end="-70"/>

        <!-- pokrcenie kolien -->
        <rle4 end="-60"/>
        <lle4 end="-60"/>

        <rle5 end="40"/>
        <lle5 end="40"/>

        <!-- torzo -->
        <rle3 end="30"/>
        <lle3 end="30"/>

      </effectors>
      <duration>400</duration>
    </phase>

    <phase name="kick_right_faster_Phase5" isFinal="true">
      <effectors>
        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>500</duration>
      <finalize>kick_right_faster_Phase6</finalize>
    </phase>
    <phase name="kick_right_faster_Phase6" isFinal="true">
      <effectors>

      </effectors>
      <duration>0</duration>
      <finalize>kick_right_faster_Phase0</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/fall_front.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="moves.xsd">
	<low_skills>
		<low_skill name="fall_front" firstPhase="fall_front">
			<type>fall</type>
			<author>Androids</author>
			<extendedFromMove></extendedFromMove>
			<description>Player falls to the front. Move is less effective.
			</description>
		</low_skill>
	</low_skills>

	<phases>
		<phase name="fall_front" next="fall_front1" isFinal="true">
			<effectors>
				<he1 end="0" />
				<he2 end="0" />
				<rae2 end="0" />
				<lae2 end="0" />
				<rae3 end="0" />
				<lae3 end="0" />
				<rae4 end="0" />
				<lae4 end="0" />
				<rle1 end="0" />
				<lle1 end="0" />
				<rle2 end="0" />
				<lle2 end="0" />
				<rle3 end="0" />
				<lle3 end="0" />
				<rle4 end="0" />
				<lle4 end="0" />
				<rle5 end="0" />
				<lle5 end="0" />
				<rle6 end="0" />
				<lle6 end="0" />
				<lae1 end="90" />
				<rae1 end="90" />
				<rle5 end="15" />
				<lle5 end="15" />
			</effectors>
			<duration>200</duration>
			<finalize>straighten</finalize>
		</phase>
		<phase name="fall_front1" next="fall_front2">
			<effectors>
				<rle5 end="20" />
				<lle5 end="20" />
			</effectors>
			<duration>200</duration>
		</phase>
		<phase name="fall_front2" isFinal="true">
			<effectors>
				<rle5 end="20" />
				<lle5 end="20" />
			</effectors>
			<duration>1000</duration>
			<finalize>fall_front2</finalize>
		</phase>
	</phases>
</robot>
