=== MrFilip26/bakalarka/Jim/moves/moves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/moves"
        xmlns:tns="http://www.example.org/moves" elementFormDefault="qualified">

  <element name="robot">
    <complexType>
      <sequence>
        <element name="constants" type="tns:constants" minOccurs="0" maxOccurs="1"/>
        <element name="low_skills" type="tns:low_skills" minOccurs="1" maxOccurs="1"/>
        <element name="phases" type="tns:phases" minOccurs="1" maxOccurs="1"/>
      </sequence>
    </complexType>

    <key name="phaseNames">
      <selector xpath="./phases/phase"></selector>
      <field xpath="@name"></field>
    </key>
    <keyref name="lowSkillAutocomplete" refer="tns:phaseNames">
      <selector xpath="./low_skills/low_skill"></selector>
      <field xpath="@firstPhase"></field>
    </keyref>
  </element>

  <xs:simpleType name="typeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="kick"/>
      <xs:enumeration value="walk"/>
      <xs:enumeration value="fall"/>
      <xs:enumeration value="look"/>
      <xs:enumeration value="stand_up"/>
      <xs:enumeration value="rotation"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <complexType name="constants">
    <sequence>
      <element name="constant" type="tns:constant" minOccurs="1" maxOccurs="unbounded"></element>
    </sequence>
  </complexType>

  <complexType name="constant">
    <attribute name="name" use="required" type="string"/>
    <attribute name="value" use="required" type="double"/>
  </complexType>

  <complexType name="low_skills">
    <sequence>
      <element name="low_skill" type="tns:low_skill" minOccurs="1" maxOccurs="unbounded"></element>
    </sequence>
  </complexType>

  <complexType name="low_skill">
    <attribute name="name" type="string" use="required"></attribute>
    <attribute name="firstPhase" type="string" use="required"></attribute>
    <sequence>
      <element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"></element>
      <element name="author" type="xs:string" minOccurs="0" maxOccurs="1"></element>
      <element name="extendedFromMove" type="xs:string" minOccurs="0" maxOccurs="1"></element>
      <element name="description" type="xs:string" minOccurs="0" maxOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="phases">
    <sequence>
      <element name="phase" type="tns:phase" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="phase">
    <sequence>
      <element name="effectors" type="tns:effectors" maxOccurs="1"/>
      <element name="duration" type="int" maxOccurs="1"/>
      <sequence>
        <element name="finalize" type="string" minOccurs="0" maxOccurs="1"/>
      </sequence>
    </sequence>
    <attribute name="name" use="required"></attribute>
    <attribute name="next" use="required"></attribute>
    <attribute name="isFinal" type="boolean"></attribute>
    <attribute name="skipIfFlag" type="string"></attribute>
    <attribute name="setFlagTrue" type="string"></attribute>
    <attribute name="setFlagFalse" type="string"></attribute>
  </complexType>

  <attributeGroup name="end">
    <attribute name="end" type="int" use="required"></attribute>
  </attributeGroup>

  <element name="joint" abstract="true">
    <complexType>
      <attribute name="end" use="required" type="int"></attribute>
    </complexType>
  </element>

  <complexType name="effectors">
    <sequence minOccurs="0" maxOccurs="22">
      <element name="he1" type="tns:he1" minOccurs="0" maxOccurs="1"></element>
      <element name="he2" type="tns:he2" minOccurs="0" maxOccurs="1"></element>
      <element name="rle1" type="tns:rle1" minOccurs="0" maxOccurs="1"></element>
      <element name="rle2" type="tns:rle2" minOccurs="0" maxOccurs="1"></element>
      <element name="rle3" type="tns:rle3" minOccurs="0" maxOccurs="1"></element>
      <element name="rle4" type="tns:rle4" minOccurs="0" maxOccurs="1"></element>
      <element name="rle5" type="tns:rle5" minOccurs="0" maxOccurs="1"></element>
      <element name="rle6" type="tns:rle6" minOccurs="0" maxOccurs="1"></element>
      <element name="rae1" type="tns:rae1" minOccurs="0" maxOccurs="1"></element>
      <element name="rae2" type="tns:rae2" minOccurs="0" maxOccurs="1"></element>
      <element name="rae3" type="tns:rae3" minOccurs="0" maxOccurs="1"></element>
      <element name="rae4" type="tns:rae4" minOccurs="0" maxOccurs="1"></element>
      <element name="lle1" type="tns:lle1" minOccurs="0" maxOccurs="1"></element>
      <element name="lle2" type="tns:lle2" minOccurs="0" maxOccurs="1"></element>
      <element name="lle3" type="tns:lle3" minOccurs="0" maxOccurs="1"></element>
      <element name="lle4" type="tns:lle4" minOccurs="0" maxOccurs="1"></element>
      <element name="lle5" type="tns:lle5" minOccurs="0" maxOccurs="1"></element>
      <element name="lle6" type="tns:lle6" minOccurs="0" maxOccurs="1"></element>
      <element name="lae1" type="tns:lae1" minOccurs="0" maxOccurs="1"></element>
      <element name="lae2" type="tns:lae2" minOccurs="0" maxOccurs="1"></element>
      <element name="lae3" type="tns:lae3" minOccurs="0" maxOccurs="1"></element>
      <element name="lae4" type="tns:lae4" minOccurs="0" maxOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="joint" abstract="true">
    <attributeGroup ref="tns:end"></attributeGroup>
  </complexType>

  <complexType name="he1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="he2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle5">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rle6">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="rae4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle5">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lle6">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae1">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae2">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae3">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>

  <complexType name="lae4">
    <complexContent>
      <extension base="tns:joint"></extension>
    </complexContent>
  </complexType>
</schema>

=== MrFilip26/bakalarka/Jim/moves/test_turn_right.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xsi:noNamespaceSchemaLocation="moves.xsd">
  <constants>
    <constant name="strafe_leg_crouch" value="30"/>
    <constant name="strafe_leg_span" value="7"/>
    <constant name="strafe_step_length" value="15"/>
  </constants>

  <low_skills>
    <low_skill name="test_turn_right" firstPhase="turn_right_big_stance"/>
  </low_skills>

  <phases>
    <phase name="turn_right_big_stance" next="start_big_turning_right">
      <effectors>
        <rle3 end="strafe_leg_crouch+30"/>
        <lle3 end="strafe_leg_crouch+30"/>
        <rle4 end="-2*strafe_leg_crouch"/>
        <lle4 end="-2*strafe_leg_crouch"/>
        <rle5 end="strafe_leg_crouch"/>
        <lle5 end="strafe_leg_crouch"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="90"/>
        <lae3 end="-90"/>
        <rae4 end="45"/>
        <lae4 end="-45"/>
      </effectors>
      <duration>500</duration>
    </phase>
    <phase name="start_big_turning_right" next="start_big_turning_right3">
      <effectors>
        <he1 end="0" computed="headAngle1"/>
        <he2 end="0" computed="headAngle2"/>
        <rle2 end="-50"/>
        <lle2 end="0"/>
        <rle6 end="4"/>
        <lle6 end="0"/>
      </effectors>
      <duration>240</duration>
    </phase>
    <phase name="start_big_turning_right3" next="start_big_turning_right4">
      <effectors>
        <he1 end="0" computed="headAngle1"/>
        <he2 end="0" computed="headAngle2"/>
        <rle2 end="0"/>
        <lle2 end="3"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>180</duration>
    </phase>
    <phase name="start_big_turning_right4" next="start_big_turning_right5">
      <effectors>
        <he1 end="0" computed="headAngle1"/>
        <he2 end="0" computed="headAngle2"/>
        <rle2 end="0"/>
        <lle2 end="5"/>
        <rle6 end="0"/>
        <lle6 end="-2"/>
      </effectors>
      <duration>160</duration>
    </phase>
    <phase name="start_big_turning_right5" next="start_big_turning_right"
           isFinal="true">
      <effectors>
        <he1 end="0" computed="headAngle1"/>
        <he2 end="0" computed="headAngle2"/>
        <rle2 end="0"/>
        <lle2 end="3"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>100</duration>
      <finalize>stop_big_turning_right</finalize>
    </phase>
    <phase name="stop_big_turning_right" setFlagTrue="in_walk_position" isFinal="true">
      <effectors>
        <he1 end="0" computed="headAngle1"/>
        <he2 end="0" computed="headAngle2"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="7"/>
        <lle2 end="-7"/>
        <rle3 end="55"/>
        <lle3 end="55"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="-7"/>
        <lle6 end="7"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="90"/>
        <lae3 end="-90"/>
        <rae4 end="45"/>
        <lae4 end="-45"/>
      </effectors>
      <duration>400</duration>
      <finalize>stop_big_turning_right</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/walk_back.xml
<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <constants>
    <!--konstanty sem-->
  </constants>
  <low_skills>
    <low_skill name="walk_back" firstPhase="walk_back_default">
      <type>walk</type>
      <author>Gabor Nagy (A55 kickers)</author>
      <extendedFromMove>walk_back</extendedFromMove>
      <description>Player performs backward walk. Move is stable and fast.</description>
    </low_skill>
  </low_skills>
  <phases>
    <phase name="walk_back_default" next="walk_back_Phase0">
      <effectors>
        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>500</duration>
    </phase>
    <phase name="walk_back_Phase0" next="walk_back_Phase1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="7"/>
        <lle2 end="-7"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="-7"/>
        <lle6 end="7"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="walk_back_Phase1" next="walk_back_Phase2">
      <effectors>
        <rle4 end="-80"/>
        <rle5 end="65"/>
        <rle3 end="10"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="walk_back_Phase2" next="walk_back_Phase3">
      <effectors>
        <rle4 end="-10"/>
        <lle4 end="-80"/>
        <rle5 end="10"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="walk_back_Phase3" next="walk_back_Phase4">
      <effectors>
        <lle4 end="-80"/>
        <lle5 end="65"/>
        <lle3 end="10"/>
        <rle4 end="-60"/>
        <rle5 end="30"/>
        <rle3 end="40"/>

      </effectors>
      <duration>400</duration>

    </phase>
    <phase name="walk_back_Phase4" next="walk_back_Phase5">
      <effectors>
        <lle4 end="-10"/>
        <rle4 end="-80"/>
        <lle5 end="10"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="walk_back_Phase5" next="walk_back_Phase2" isFinal="true">
      <effectors>
        <rle4 end="-80"/>
        <rle5 end="65"/>
        <rle3 end="10"/>
        <lle4 end="-60"/>
        <lle5 end="30"/>
        <lle3 end="40"/>
      </effectors>
      <duration>400</duration>
      <finalize>walk_back_Phase6</finalize>
    </phase>
    <phase name="walk_back_Phase6" isFinal="true">
      <effectors>
        <he2 end="0"/>

        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>

        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="40"/>
        <lle3 end="40"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
      </effectors>
      <duration>500</duration>
      <finalize>walk_back_Phase0</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/filipskuska.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
	<low_skills>
		<low_skill name="filipskuska" firstPhase="filipskuska">
			<type>skuska</type>
			<author>Filip Blanarik</author>
			<extendedFromMove></extendedFromMove>
			<description>Hrac hybe rukami a hlavou</description>
		</low_skill>
	</low_skills>
	
  <phases>
    <phase name="filipskuska" next="filipskuska1">
      <effectors>
	<he1 end="0" />
		<he2 end="45" />
	<rae2 end="0" />
	<lae2 end="0" />
	<rae3 end="0" />
	<lae3 end="0" />
	<rae4 end="0" />
	<lae4 end="0" />
	<rle1 end="0" />
	<lle1 end="0" />
	<rle2 end="0" />
	<lle2 end="0" />
	<rle3 end="0" />
	<lle3 end="0" />
	<rle4 end="0" />
	<lle4 end="0" />
	<rle5 end="0" />
	<lle5 end="0" />
	<rle6 end="0" />
	<lle6 end="0" />
        <lae1 end="90" />
        <rae1 end="90" />
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="filipskuska1" next="filipskuska2">
      <effectors>
        <he2 end="-45" />
	    <rae1 end="0" />
		<lae1 end="0" />
      </effectors>
      <duration>400</duration>
    </phase>
	<phase name="filipskuska2" next="filipskuska3">
      <effectors>
        <he2 end="45" />
	    <rae1 end="90" />
		<lae1 end="90" />
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="filipskuska3" isFinal="true">
      <effectors>
        <he2 end="0" />
	    <rae1 end="0" />
		<lae1 end="0" />
      </effectors>
      <duration>400</duration>
      <finalize>filipskuska</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/nahlavu.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <low_skills>
    <low_skill name="nahlavu" firstPhase="nahlavu">
      <type>fall</type>
      <author>Androids</author>
      <extendedFromMove></extendedFromMove>
      <description>Player falls to the front. Move is less effective.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="nahlavu" next="nahlavu1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rae3 end="0"/>
        <lae3 end="0"/>
        <rae4 end="0"/>
        <lae4 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="0"/>
        <lle3 end="0"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="0"/>
        <lle5 end="0"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
        <lae1 end="-90"/>
        <rae1 end="-90"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="nahlavu1" next="nahlavu2">
      <effectors>

      </effectors>
      <duration>100</duration>
    </phase>
    <phase name="nahlavu2" next="nahlavu3">
      <effectors>
        <lae1 end="28"/>
        <rae1 end="28"/>
        <rle3 end="100"/>
        <lle3 end="100"/>
        <rle4 end="-120"/>
        <lle4 end="-120"/>

      </effectors>
      <duration>2000</duration>
    </phase>
    <phase name="nahlavu3" next="nahlavu4">
      <effectors>
        <rle2 end="-120"/>
        <lle2 end="120"/>

        <rle3 end="60"/>
        <lle3 end="60"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="-90"/>
        <lle5 end="-90"/>
        <rle1 end="-90"/>
        <lle1 end="-90"/>
      </effectors>
      <duration>1000</duration>
    </phase>
    <phase name="nahlavu4" next="nahlavu5">
      <effectors>
        <rle2 end="0"/>
        <lle2 end="0"/>

        <rle3 end="0"/>
        <lle3 end="0"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="0"/>
        <lle5 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>

      </effectors>
      <duration>1500</duration>
    </phase>
    <phase name="nahlavu5" next="nahlavu6">
      <effectors>
        <rle2 end="-120"/>
        <lle2 end="120"/>

        <rle3 end="60"/>
        <lle3 end="60"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="-90"/>
        <lle5 end="-90"/>
        <rle1 end="-90"/>
        <lle1 end="-90"/>

      </effectors>
      <duration>1500</duration>
    </phase>
    <phase name="nahlavu6" next="nahlavu7">
      <effectors>
        <rle2 end="0"/>
        <lle2 end="0"/>

        <rle3 end="0"/>
        <lle3 end="0"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="0"/>
        <lle5 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>

      </effectors>
      <duration>1500</duration>
    </phase>
    <phase name="nahlavu7" next="nahlavu8">
      <effectors>
        <rle2 end="-120"/>
        <lle2 end="120"/>

        <rle3 end="60"/>
        <lle3 end="60"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="-90"/>
        <lle5 end="-90"/>
        <rle1 end="-90"/>
        <lle1 end="-90"/>

      </effectors>
      <duration>1500</duration>
    </phase>
    <phase name="nahlavu8" next="nahlavu9">
      <effectors>
        <rle2 end="0"/>
        <lle2 end="0"/>

        <rle3 end="0"/>
        <lle3 end="0"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="0"/>
        <lle5 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>

      </effectors>
      <duration>1500</duration>
    </phase>

    <phase name="nahlavu9" next="nahlavuf">
      <effectors>
        <lae1 end="28"/>
        <rae1 end="28"/>
        <rle3 end="100"/>
        <lle3 end="100"/>
        <rle4 end="-120"/>
        <lle4 end="-120"/>

      </effectors>
      <duration>2000</duration>
    </phase>


    <phase name="nahlavuf" isFinal="true">
      <effectors>

      </effectors>
      <duration>100</duration>
      <finalize>nahlavu</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/walk_forward.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <low_skills>
    <low_skill name="walk_forward" firstPhase="walk_forward_1">
      <type>walk</type>
      <author>Gabor Nagy (A55 Kickers)</author>
      <extendedFromMove>walk_fine_fast2_optimized2acc</extendedFromMove>
      <description>Player performs straight walk. Move is very stable and fast.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="walk_forward_1" next="walk_forward_2">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="9"/>
        <lle2 end="-9"/>
        <rle3 end="25"/>
        <lle3 end="25"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="30"/>
        <lle5 end="30"/>
        <rle6 end="-9"/>
        <lle6 end="9"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>
      </effectors>
      <duration>620</duration>
    </phase>

    <!-- accelerate -->

    <phase name="walk_forward_2" next="walk_forward_3">
      <effectors>
        <rle3 end="55"/>
        <rle4 end="-75"/>
        <rle5 end="35"/>
        <lle3 end="25"/>
        <lle4 end="-40"/>
        <lle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_3" next="walk_forward_4">
      <effectors>
        <rle3 end="60"/>
        <rle4 end="-61"/>
        <rle5 end="18"/>
        <lle3 end="30"/>
        <lle4 end="-65"/>
        <lle5 end="50"/>
        <rae1 end="-110"/>
        <lae1 end="-70"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_4" next="walk_forward_5">
      <effectors>
        <lle3 end="55"/>
        <lle4 end="-75"/>
        <lle5 end="35"/>
        <rle3 end="25"/>
        <rle4 end="-40"/>
        <rle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_5" next="walk_forward_6" isFinal="true">
      <effectors>
        <lle3 end="60"/>
        <lle4 end="-61"/>
        <lle5 end="18"/>
        <rle3 end="30"/>
        <rle4 end="-65"/>
        <rle5 end="50"/>
        <rae1 end="-70"/>
        <lae1 end="-110"/>
      </effectors>
      <duration>200</duration>
      <finalize>straighten</finalize>
    </phase>
    <!-- normal move -->

    <phase name="walk_forward_6" next="walk_forward_7">
      <effectors>
        <rle3 end="55"/>
        <rle4 end="-75"/>
        <rle5 end="35"/>
        <lle3 end="25"/>
        <lle4 end="-40"/>
        <lle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_forward_7" next="walk_forward_8">
      <effectors>
        <rle3 end="60"/>
        <rle4 end="-61"/>
        <rle5 end="18"/>
        <lle3 end="30"/>
        <lle4 end="-65"/>
        <lle5 end="50"/>
        <rae1 end="-110"/>
        <lae1 end="-70"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_forward_8" next="walk_forward_9">
      <effectors>
        <lle3 end="55"/>
        <lle4 end="-75"/>
        <lle5 end="35"/>
        <rle3 end="25"/>
        <rle4 end="-40"/>
        <rle5 end="30"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>150</duration>
    </phase>
    <phase name="walk_forward_9" next="walk_forward_6" isFinal="true">
      <effectors>
        <lle3 end="60"/>
        <lle4 end="-61"/>
        <lle5 end="18"/>
        <rle3 end="30"/>
        <rle4 end="-65"/>
        <rle5 end="50"/>
        <rae1 end="-70"/>
        <lae1 end="-110"/>
      </effectors>
      <duration>150</duration>
      <finalize>walk_forward_10</finalize>
    </phase>

    <phase name="walk_forward_10" next="walk_forward_11">
      <effectors>

        <rle3 end="55"/>
        <rle4 end="-75"/>
        <rle5 end="35"/>
        <lle3 end="25"/>
        <lle4 end="-40"/>
        <lle5 end="28"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_11" next="walk_forward_12">
      <effectors>
        <rle3 end="60"/>
        <rle4 end="-61"/>
        <rle5 end="18"/>
        <lle3 end="30"/>
        <lle4 end="-65"/>
        <lle5 end="50"/>
        <rae1 end="-110"/>
        <lae1 end="-70"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_12" next="walk_forward_13">
      <effectors>
        <lle3 end="55"/>
        <lle4 end="-75"/>
        <lle5 end="33"/>
        <rle3 end="25"/>
        <rle4 end="-40"/>
        <rle5 end="26"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_13" next="walk_forward_14">
      <effectors>
        <lle3 end="60"/>
        <lle4 end="-61"/>
        <lle5 end="18"/>
        <rle3 end="30"/>
        <rle4 end="-65"/>
        <rle5 end="50"/>
        <rae1 end="-70"/>
        <lae1 end="-110"/>
      </effectors>
      <duration>200</duration>
    </phase>
    <phase name="walk_forward_13" isFinal="true">
      <effectors>

        <he1 end="0"/>
        <he2 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="9"/>
        <lle2 end="-9"/>
        <rle3 end="45"/>
        <lle3 end="45"/>
        <rle4 end="-60"/>
        <lle4 end="-60"/>
        <rle5 end="31"/>
        <lle5 end="31"/>
        <rle6 end="-9"/>
        <lle6 end="9"/>
        <rae1 end="-90"/>
        <lae1 end="-90"/>
        <rae2 end="-10"/>
        <lae2 end="10"/>
        <rae3 end="80"/>
        <lae3 end="-80"/>
        <rae4 end="60"/>
        <lae4 end="-60"/>
      </effectors>
      <duration>620</duration>
      <finalize>walk_forward_1</finalize>
    </phase>
  </phases>
</robot>

=== MrFilip26/bakalarka/Jim/moves/hlavaaruky.xml
<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="moves.xsd">
  <low_skills>
    <low_skill name="hlavaaruky" firstPhase="hlavaaruky">
      <type>fall</type>
      <author>Androids</author>
      <extendedFromMove></extendedFromMove>
      <description>Player falls to the front. Move is less effective.</description>
    </low_skill>
  </low_skills>

  <phases>
    <phase name="hlavaaruky" next="hlavaaruky1">
      <effectors>
        <he1 end="0"/>
        <he2 end="0"/>
        <rae2 end="0"/>
        <lae2 end="0"/>
        <rae3 end="0"/>
        <lae3 end="0"/>
        <rae4 end="0"/>
        <lae4 end="0"/>
        <rle1 end="0"/>
        <lle1 end="0"/>
        <rle2 end="0"/>
        <lle2 end="0"/>
        <rle3 end="0"/>
        <lle3 end="0"/>
        <rle4 end="0"/>
        <lle4 end="0"/>
        <rle5 end="0"/>
        <lle5 end="0"/>
        <rle6 end="0"/>
        <lle6 end="0"/>
        <lae1 end="-90"/>
        <rae1 end="-90"/>
      </effectors>
      <duration>400</duration>
    </phase>
    <phase name="hlavaaruky1" next="hlavaaruky2">
      <effectors>
        <he1 end="-90"/>
        <rae1 end="-180"/>
        <lae1 end="180"/>
      </effectors>
      <duration>800</duration>
    </phase>
    <phase name="hlavaaruky2" next="hlavaaruky3">
      <effectors>
        <he1 end="90"/>
        <rae1 end="180"/>
        <lae1 end="-180"/>
      </effectors>
      <duration>1600</duration>
    </phase>
    <phase name="hlavaaruky3" isFinal="true">
      <effectors>

      </effectors>
      <duration>100</duration>
      <finalize>hlavaaruky</finalize>
    </phase>
  </phases>
</robot>
